# Generated by Django 3.0.6 on 2020-06-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=20)),
                ('fileName', models.CharField(max_length=500)),
                ('fileContent', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='FileSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=20)),
                ('fileName', models.CharField(max_length=100)),
                ('filePath', models.CharField(max_length=300)),
                ('lastModifiedDate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='HashList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=20)),
                ('filePath', models.CharField(max_length=300)),
                ('fileName', models.CharField(max_length=100)),
                ('hash', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
